CREATE TABLE IF NOT EXISTS perguntas (
    id                  SERIAL PRIMARY KEY,
    texto               TEXT            NOT NULL,
    secao               VARCHAR(100)    NOT NULL DEFAULT 'Anamnesis',
    categoria           VARCHAR(100)    NOT NULL,
    resposta_padrao     TEXT            NOT NULL,
    ativo               BOOLEAN         NOT NULL DEFAULT TRUE,
    ordem_exibicao      INTEGER         NOT NULL DEFAULT 0,
    criado_em           TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    atualizado_em       TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

INSERT INTO perguntas
(texto, secao, categoria, resposta_padrao, ordem_exibicao)
VALUES
('¿Cómo te llamás?','Datos Personales','Identificación','Me llamo Juan.',1),
('¿Cuántos años tenés?','Datos Personales','Identificación','Tengo 30 años.',2),
('¿Qué fecha de nacimiento tenés?','Datos Personales','Identificación','Nací el 12 de mayo de 1995.',3),
('¿Con qué género te identificás?','Datos Personales','Identificación','Me identifico como varón.',4),
('¿Tenés pareja?','Datos Personales','Contexto social','Sí, tengo pareja.',5),
('¿Vivís solo o con alguien?','Datos Personales','Contexto social','Vivo con mi pareja.',6),
('¿Con quién vivís actualmente?','Datos Personales','Contexto social','Vivo con mi pareja.',7),
('¿Tenés hijos?','Datos Personales','Contexto social','No, no tengo hijos.',8),
('¿En qué ciudad vivís?','Datos Personales','Identificación','Vivo en Buenos Aires.',9),
('¿Hace mucho vivís ahí?','Datos Personales','Contexto social','Sí, hace varios años.',10),
('¿A qué te dedicás?','Datos Personales','Contexto social','Trabajo en una oficina.',11),
('¿Estás trabajando actualmente?','Datos Personales','Contexto social','Sí, estoy trabajando.',12),
('¿Estás estudiando algo?','Datos Personales','Contexto social','No, en este momento no.',13),
('¿Cómo es un día normal para vos?','Datos Personales','Contexto social','Bastante tranquilo.',14),
('¿Tenés obra social o prepaga?','Datos Personales','Contexto social','Sí, tengo obra social.',15),
('¿Sos de venir seguido al médico?','Datos Personales','Contexto social','Sí, vengo para controles.',16),
('¿Tenés algún médico de cabecera?','Datos Personales','Contexto social','Sí, tengo médico de cabecera.',17),
('¿Vivís en casa o departamento?','Datos Personales','Contexto social','Vivo en un departamento.',18),
('¿Subís muchas escaleras en tu casa o trabajo?','Datos Personales','Contexto social','No, no muchas.',19),
('¿Cómo venís de apoyo en casa?','Datos Personales','Contexto social','Bien, tengo apoyo.',20),
('¿Quién te acompaña cuando te sentís mal?','Datos Personales','Contexto social','Mi pareja o mi familia.',21),
('¿Tenés algún familiar o amigo cerca?','Datos Personales','Contexto social','Sí, tengo familiares cerca.',22),
('¿Cómo llegaste hoy a la consulta?','Motivo de Consulta','Motivo de consulta','Vine por mis propios medios.',23),
('¿Qué te trae hoy a la consulta?','Motivo de Consulta','Motivo de consulta','Vine para un control general.',24),
('¿Te sentís mal por algo en especial?','Motivo de Consulta','Motivo de consulta','No, vine para controlarme.',25),
('¿Hay algo que te preocupe hoy?','Motivo de Consulta','Motivo de consulta','No, nada en particular.',26),
('¿Viniste por control o por algún síntoma?','Motivo de Consulta','Motivo de consulta','Vine por control.',27),
('¿Hace cuánto querías hacer este control?','Motivo de Consulta','Motivo de consulta','Hace unas semanas.',28),
('¿Es la primera vez que consultás por esto?','Motivo de Consulta','Motivo de consulta','Sí, es la primera vez.',29),
('¿Esto empezó hoy o ya viene de antes?','Motivo de Consulta','Motivo de consulta','No empezó hoy, vine por control.',30),
('¿Te pasó algo estos días que te hiciera venir?','Motivo de Consulta','Motivo de consulta','No, solo quería controlarme.',31),
('¿Te derivó alguien o viniste por tu cuenta?','Motivo de Consulta','Motivo de consulta','Vine por mi cuenta.',32),
('¿Te lo pidió algún médico?','Motivo de Consulta','Motivo de consulta','No, vine por decisión propia.',33),
('¿Hay algún síntoma que quieras revisar?','Motivo de Consulta','Motivo de consulta','No, ningún síntoma puntual.',34),
('¿Tenés alguna molestia ahora?','Motivo de Consulta','Motivo de consulta','No, ahora no.',35),
('¿Te sentís distinto a lo habitual?','Motivo de Consulta','Motivo de consulta','No, me siento bien.',36),
('¿Querés hacerte un chequeo general?','Motivo de Consulta','Motivo de consulta','Sí, vine por eso.',37),
('¿Hace cuánto no te hacés un control?','Motivo de Consulta','Motivo de consulta','Hace alrededor de un año.',38),
('¿Venís por un problema nuevo o por seguimiento?','Motivo de Consulta','Motivo de consulta','Vengo por un control general.',39),
('¿Hubo algo en tus estudios anteriores que quieras revisar?','Motivo de Consulta','Motivo de consulta','No, estaba todo bien.',40),
('¿Te recomendaron hacer controles por edad o rutina?','Motivo de Consulta','Motivo de consulta','Sí, por rutina.',41),
('¿Esperabas esta consulta por algo puntual?','Motivo de Consulta','Motivo de consulta','No, solo para control.',42),
('¿Hay algo que quisieras preguntar hoy?','Motivo de Consulta','Motivo de consulta','No, nada en especial.',43),
('¿Te preocupa alguna enfermedad en particular?','Motivo de Consulta','Motivo de consulta','No, ninguna en particular.',44),
('¿Notaste algún cambio en tu salud últimamente?','Motivo de Consulta','Motivo de consulta','No, me siento igual que siempre.',45),
('¿Tenés dolor en este momento?','Motivo de Consulta','Motivo de consulta','No, no tengo dolor.',46),
('¿Tenés fiebre o sensación de fiebre?','Motivo de Consulta','Motivo de consulta','No.',47),
('¿Te falta el aire o te agitás más de lo normal?','Motivo de Consulta','Motivo de consulta','No.',48),
('¿Estás tosiendo o resfriado?','Motivo de Consulta','Motivo de consulta','No.',49),
('¿Tuviste vómitos, diarrea o dolor de panza?','Motivo de Consulta','Motivo de consulta','No.',50),
('¿Te sentiste mareado o con debilidad?','Motivo de Consulta','Motivo de consulta','No.',51),
('¿Dormís bien últimamente?','Motivo de Consulta','Motivo de consulta','Sí, duermo bien.',52),
('¿Venís porque te pasó algo raro o distinto?','Motivo de Consulta','Motivo de consulta','No.',53),
('¿Esto te impide hacer tu vida normal?','Motivo de Consulta','Motivo de consulta','No.',54),
('¿Querés aprovechar la consulta para revisar tu salud en general?','Motivo de Consulta','Motivo de consulta','Sí.',55),
('¿Tuviste fiebre estos días?','Historia de la Enfermedad Actual','Síntomas generales','No.',56),
('¿Llegaste a tomarte la temperatura?','Historia de la Enfermedad Actual','Síntomas generales','No hizo falta.',57),
('¿Sentiste escalofríos?','Historia de la Enfermedad Actual','Síntomas generales','No.',58),
('¿Tuviste sudoración de más?','Historia de la Enfermedad Actual','Síntomas generales','No.',59),
('¿Te sentiste más cansado de lo normal?','Historia de la Enfermedad Actual','Síntomas generales','No.',60),
('¿Te falta energía para tus cosas de todos los días?','Historia de la Enfermedad Actual','Síntomas generales','No.',61),
('¿Te sentiste decaído?','Historia de la Enfermedad Actual','Síntomas generales','No.',62),
('¿Tuviste malestar general?','Historia de la Enfermedad Actual','Síntomas generales','No.',63),
('¿Bajaste de peso sin querer?','Historia de la Enfermedad Actual','Síntomas generales','No.',64),
('¿Subiste de peso últimamente sin proponértelo?','Historia de la Enfermedad Actual','Síntomas generales','No.',65),
('¿Te cambió el apetito?','Historia de la Enfermedad Actual','Síntomas generales','No, como normal.',66),
('¿Tenés menos ganas de comer?','Historia de la Enfermedad Actual','Síntomas generales','No.',67),
('¿Tenés más hambre de lo habitual?','Historia de la Enfermedad Actual','Síntomas generales','No.',68),
('¿Tuviste sed de más?','Historia de la Enfermedad Actual','Síntomas generales','No.',69),
('¿Sentiste la boca seca seguido?','Historia de la Enfermedad Actual','Síntomas generales','No.',70),
('¿Dormís bien a la noche?','Historia de la Enfermedad Actual','Síntomas generales','Sí, duermo bien.',71),
('¿Te cuesta quedarte dormido?','Historia de la Enfermedad Actual','Síntomas generales','No.',72),
('¿Te despertás mucho de noche?','Historia de la Enfermedad Actual','Síntomas generales','No.',73),
('¿Te levantás descansado?','Historia de la Enfermedad Actual','Síntomas generales','Sí.',74),
('¿Notaste que rendís menos durante el día?','Historia de la Enfermedad Actual','Síntomas generales','No.',75),
('¿Te agitás más fácil que antes?','Historia de la Enfermedad Actual','Síntomas generales','No.',76),
('¿Sentís debilidad en general?','Historia de la Enfermedad Actual','Síntomas generales','No.',77),
('¿Te mareaste en algún momento?','Historia de la Enfermedad Actual','Síntomas generales','No.',78),
('¿Sentiste que te ibas a desmayar?','Historia de la Enfermedad Actual','Síntomas generales','No.',79),
('¿Llegaste a desmayarte?','Historia de la Enfermedad Actual','Síntomas generales','No.',80),
('¿Tuviste náuseas?','Historia de la Enfermedad Actual','Síntomas generales','No.',81),
('¿Tuviste vómitos?','Historia de la Enfermedad Actual','Síntomas generales','No.',82),
('¿Tuviste diarrea?','Historia de la Enfermedad Actual','Síntomas generales','No.',83),
('¿Estás yendo de cuerpo normal?','Historia de la Enfermedad Actual','Síntomas generales','Sí, normal.',84),
('¿Estás orinando normal?','Historia de la Enfermedad Actual','Síntomas generales','Sí, normal.',85),
('¿Notaste algún cambio raro en la piel?','Historia de la Enfermedad Actual','Síntomas generales','No.',86),
('¿Te salió alguna roncha o sarpullido?','Historia de la Enfermedad Actual','Síntomas generales','No.',87),
('¿Tuviste picazón?','Historia de la Enfermedad Actual','Síntomas generales','No.',88),
('¿Te sentiste hinchado?','Historia de la Enfermedad Actual','Síntomas generales','No.',89),
('¿Notaste hinchazón en piernas, manos o cara?','Historia de la Enfermedad Actual','Síntomas generales','No.',90),
('¿Te sentís igual que de costumbre?','Historia de la Enfermedad Actual','Síntomas generales','Sí.',91),
('¿Hay algo en tu cuerpo que sientas distinto?','Historia de la Enfermedad Actual','Síntomas generales','No.',92),
('¿Sentís dolor en alguna parte del cuerpo?','Historia de la Enfermedad Actual','Dolor','No.',93),
('¿Te duele ahora o fue en otro momento?','Historia de la Enfermedad Actual','Dolor','Ahora no.',94),
('¿Dónde te duele?','Historia de la Enfermedad Actual','Dolor','No me duele en ningún lado.',95),
('¿El dolor es en un solo lugar o en varios?','Historia de la Enfermedad Actual','Dolor','No tengo dolor.',96),
('¿Desde cuándo te duele?','Historia de la Enfermedad Actual','Dolor','No me duele.',97),
('¿Fue algo de golpe o empezó de a poco?','Historia de la Enfermedad Actual','Dolor','No aplica.',98),
('¿Te duele todo el tiempo o va y viene?','Historia de la Enfermedad Actual','Dolor','No aplica.',99),
('¿Cuánto te duele del 0 al 10?','Historia de la Enfermedad Actual','Dolor','0.',100),
('¿Cómo es el dolor?','Historia de la Enfermedad Actual','Dolor','No tengo dolor.',101),
('¿Es punzante, quemante, opresivo o tipo cólico?','Historia de la Enfermedad Actual','Dolor','No aplica.',102),
('¿El dolor se corre a otro lado?','Historia de la Enfermedad Actual','Dolor','No.',103),
('¿Hay algo que lo empeore?','Historia de la Enfermedad Actual','Dolor','No aplica.',104),
('¿Hay algo que lo alivie?','Historia de la Enfermedad Actual','Dolor','No aplica.',105),
('¿Te duele al moverte?','Historia de la Enfermedad Actual','Dolor','No.',106),
('¿Te duele cuando respirás?','Historia de la Enfermedad Actual','Dolor','No.',107),
('¿Te duele al tocarte esa zona?','Historia de la Enfermedad Actual','Dolor','No.',108),
('¿El dolor te despierta a la noche?','Historia de la Enfermedad Actual','Dolor','No.',109),
('¿Te impide hacer tu vida normal?','Historia de la Enfermedad Actual','Dolor','No.',110),
('¿Tomaste algo para el dolor?','Historia de la Enfermedad Actual','Dolor','No hizo falta.',111),
('¿Te sirvió lo que tomaste?','Historia de la Enfermedad Actual','Dolor','No aplica.',112),
('¿Ya te había pasado algo parecido antes?','Historia de la Enfermedad Actual','Dolor','No.',113),
('¿Con qué lo relacionás?','Historia de la Enfermedad Actual','Dolor','Con nada en particular.',114),
('¿Te duele la cabeza?','Historia de la Enfermedad Actual','Dolor','No.',115),
('¿Te duele el cuello?','Historia de la Enfermedad Actual','Dolor','No.',116),
('¿Te duele el pecho?','Historia de la Enfermedad Actual','Dolor','No.',117),
('¿Te duele la panza?','Historia de la Enfermedad Actual','Dolor','No.',118),
('¿Te duele la espalda?','Historia de la Enfermedad Actual','Dolor','No.',119),
('¿Te duelen las piernas o los brazos?','Historia de la Enfermedad Actual','Dolor','No.',120),
('¿Te duelen las articulaciones?','Historia de la Enfermedad Actual','Dolor','No.',121),
('¿Te duelen los músculos?','Historia de la Enfermedad Actual','Dolor','No.',122),
('¿Tenés ardor en alguna parte?','Historia de la Enfermedad Actual','Dolor','No.',123),
('¿Sentís pinchazos o calambres?','Historia de la Enfermedad Actual','Dolor','No.',124),
('¿El dolor apareció después de comer?','Historia de la Enfermedad Actual','Dolor','No.',125),
('¿El dolor apareció después de hacer esfuerzo?','Historia de la Enfermedad Actual','Dolor','No.',126),
('¿El dolor apareció después de algún golpe?','Historia de la Enfermedad Actual','Dolor','No.',127),
('¿Te preocupa algún dolor aunque sea leve?','Historia de la Enfermedad Actual','Dolor','No.',128),
('¿Sentís pesadez o molestia más que dolor?','Historia de la Enfermedad Actual','Dolor','No.',129),
('¿Notaste sensibilidad rara en alguna zona?','Historia de la Enfermedad Actual','Dolor','No.',130),
('¿Hay alguna postura que te moleste?','Historia de la Enfermedad Actual','Dolor','No.',131),
('¿Hay algún movimiento que te provoque dolor?','Historia de la Enfermedad Actual','Dolor','No.',132),
('¿Sentís molestias al hacer ejercicio?','Historia de la Enfermedad Actual','Dolor','No.',133),
('¿Después de descansar seguís con molestias?','Historia de la Enfermedad Actual','Dolor','No.',134),
('¿Tenés tos?','Historia de la Enfermedad Actual','Respiratorio','No.',135),
('¿Desde cuándo estás con tos?','Historia de la Enfermedad Actual','Respiratorio','No tengo tos.',136),
('¿La tos es seca o con flema?','Historia de la Enfermedad Actual','Respiratorio','No aplica.',137),
('¿Tosés de día, de noche o todo el tiempo?','Historia de la Enfermedad Actual','Respiratorio','No aplica.',138),
('¿La tos te despierta a la noche?','Historia de la Enfermedad Actual','Respiratorio','No.',139),
('¿La tos apareció de golpe o de a poco?','Historia de la Enfermedad Actual','Respiratorio','No aplica.',140),
('¿Sentís flema o moco en el pecho?','Historia de la Enfermedad Actual','Respiratorio','No.',141),
('¿Sacás flema cuando tosés?','Historia de la Enfermedad Actual','Respiratorio','No.',142),
('¿De qué color es la flema?','Historia de la Enfermedad Actual','Respiratorio','No aplica.',143),
('¿La flema tiene sangre?','Historia de la Enfermedad Actual','Respiratorio','No.',144),
('¿Te falta el aire?','Historia de la Enfermedad Actual','Respiratorio','No.',145),
('¿Te falta el aire en reposo o al moverte?','Historia de la Enfermedad Actual','Respiratorio','No me falta el aire.',146),
('¿Te agitás más fácil que antes?','Historia de la Enfermedad Actual','Respiratorio','No.',147),
('¿Te cuesta respirar hondo?','Historia de la Enfermedad Actual','Respiratorio','No.',148),
('¿Sentís silbidos al respirar?','Historia de la Enfermedad Actual','Respiratorio','No.',149),
('¿Sentís opresión en el pecho al respirar?','Historia de la Enfermedad Actual','Respiratorio','No.',150),
('¿Te duele el pecho cuando respirás?','Historia de la Enfermedad Actual','Respiratorio','No.',151),
('¿Sentís que te ahogás al acostarte?','Historia de la Enfermedad Actual','Respiratorio','No.',152),
('¿Dormís con varias almohadas para respirar mejor?','Historia de la Enfermedad Actual','Respiratorio','No.',153),
('¿Te despertás de noche con falta de aire?','Historia de la Enfermedad Actual','Respiratorio','No.',154),
('¿Te falta el aire al subir escaleras?','Historia de la Enfermedad Actual','Respiratorio','No.',155),
('¿Te falta el aire al caminar rápido?','Historia de la Enfermedad Actual','Respiratorio','No.',156),
('¿Podés hacer actividad física como siempre?','Historia de la Enfermedad Actual','Respiratorio','Sí.',157),
('¿Notaste que bajó tu resistencia al esfuerzo?','Historia de la Enfermedad Actual','Respiratorio','No.',158),
('¿Estuviste resfriado estos días?','Historia de la Enfermedad Actual','Respiratorio','No.',159),
('¿Tenés mocos o congestión?','Historia de la Enfermedad Actual','Respiratorio','No.',160),
('¿Te duele la garganta?','Historia de la Enfermedad Actual','Respiratorio','No.',161),
('¿Te cambió la voz?','Historia de la Enfermedad Actual','Respiratorio','No.',162),
('¿Te quedaste sin aire al hablar?','Historia de la Enfermedad Actual','Respiratorio','No.',163),
('¿Te pasó después de hacer ejercicio?','Historia de la Enfermedad Actual','Respiratorio','No.',164),
('¿Te pasó después de estar al frío?','Historia de la Enfermedad Actual','Respiratorio','No.',165),
('¿Te pasa con humo, polvo o perfumes?','Historia de la Enfermedad Actual','Respiratorio','No.',166),
('¿Sentís dolor o ardor al toser?','Historia de la Enfermedad Actual','Respiratorio','No.',167),
('¿La respiración te hace ruido?','Historia de la Enfermedad Actual','Respiratorio','No.',168),
('¿Respirás normal por la nariz?','Historia de la Enfermedad Actual','Respiratorio','Sí.',169),
('¿Tuviste contacto con alguien resfriado o con tos?','Historia de la Enfermedad Actual','Respiratorio','No.',170),
('¿Sentís puntadas en el pecho al respirar?','Historia de la Enfermedad Actual','Respiratorio','No.',171),
('¿Te sentís congestionado del pecho?','Historia de la Enfermedad Actual','Respiratorio','No.',172),
('¿Tenés dolor en el pecho?','Historia de la Enfermedad Actual','Cardiovascular','No.',173),
('¿Dónde te duele el pecho?','Historia de la Enfermedad Actual','Cardiovascular','No me duele.',174),
('¿Desde cuándo te duele el pecho?','Historia de la Enfermedad Actual','Cardiovascular','No aplica.',175),
('¿Cómo es ese dolor en el pecho?','Historia de la Enfermedad Actual','Cardiovascular','No aplica.',176),
('¿El dolor se corre al brazo, cuello o mandíbula?','Historia de la Enfermedad Actual','Cardiovascular','No.',177),
('¿Te agarra con esfuerzo o también en reposo?','Historia de la Enfermedad Actual','Cardiovascular','No aplica.',178),
('¿Se te pasa al frenar o descansar?','Historia de la Enfermedad Actual','Cardiovascular','No aplica.',179),
('¿Te dura mucho o se va rápido?','Historia de la Enfermedad Actual','Cardiovascular','No aplica.',180),
('¿Te falta el aire junto con ese dolor?','Historia de la Enfermedad Actual','Cardiovascular','No.',181),
('¿Te agarraron palpitaciones?','Historia de la Enfermedad Actual','Cardiovascular','No.',182),
('¿Sentís que el corazón late fuerte o raro?','Historia de la Enfermedad Actual','Cardiovascular','No.',183),
('¿Te late muy rápido a veces?','Historia de la Enfermedad Actual','Cardiovascular','No.',184),
('¿Te late desordenado o salteado?','Historia de la Enfermedad Actual','Cardiovascular','No.',185),
('¿Las palpitaciones aparecen en reposo o con esfuerzo?','Historia de la Enfermedad Actual','Cardiovascular','No aplica.',186),
('¿Cuánto duran cuando aparecen?','Historia de la Enfermedad Actual','Cardiovascular','No aplica.',187),
('¿Se acompañan de mareo o falta de aire?','Historia de la Enfermedad Actual','Cardiovascular','No.',188),
('¿Sentiste que te bajó la presión?','Historia de la Enfermedad Actual','Cardiovascular','No.',189),
('¿Te mareaste al levantarte?','Historia de la Enfermedad Actual','Cardiovascular','No.',190),
('¿Llegaste a desmayarte?','Historia de la Enfermedad Actual','Cardiovascular','No.',191),
('¿Se te hinchan las piernas o los tobillos?','Historia de la Enfermedad Actual','Cardiovascular','No.',192),
('¿Notaste hinchazón al final del día?','Historia de la Enfermedad Actual','Cardiovascular','No.',193),
('¿Se te marcan las medias en los tobillos?','Historia de la Enfermedad Actual','Cardiovascular','No.',194),
('¿Notaste que una pierna se hincha más que la otra?','Historia de la Enfermedad Actual','Cardiovascular','No.',195),
('¿Te cansás más con esfuerzos que antes?','Historia de la Enfermedad Actual','Cardiovascular','No.',196),
('¿Te cuesta subir escaleras por cansancio o agitación?','Historia de la Enfermedad Actual','Cardiovascular','No.',197),
('¿Tenés que frenar cuando caminás por cansancio?','Historia de la Enfermedad Actual','Cardiovascular','No.',198),
('¿Podés hacer ejercicio como siempre?','Historia de la Enfermedad Actual','Cardiovascular','Sí.',199),
('¿Sentís pesadez en el pecho con esfuerzo?','Historia de la Enfermedad Actual','Cardiovascular','No.',200),
('¿Te duele o molesta el pecho después de comer o moverte?','Historia de la Enfermedad Actual','Cardiovascular','No.',201),
('¿Sentís latidos en el cuello o en el pecho?','Historia de la Enfermedad Actual','Cardiovascular','No.',202),
('¿Te despertás de noche con palpitaciones o agitado?','Historia de la Enfermedad Actual','Cardiovascular','No.',203),
('¿Dormís acostado normal?','Historia de la Enfermedad Actual','Cardiovascular','Sí.',204),
('¿Notaste labios o dedos morados alguna vez?','Historia de la Enfermedad Actual','Cardiovascular','No.',205),
('¿Se te enfrían mucho las manos o los pies?','Historia de la Enfermedad Actual','Cardiovascular','No.',206),
('¿Te duele la pantorrilla al caminar?','Historia de la Enfermedad Actual','Cardiovascular','No.',207),
('¿Se te pasa cuando parás?','Historia de la Enfermedad Actual','Cardiovascular','No aplica.',208),
('¿Te tomaste la presión últimamente?','Historia de la Enfermedad Actual','Cardiovascular','Sí, estaba normal.',209),
('¿Alguna vez te dijeron que tenías la presión alta?','Historia de la Enfermedad Actual','Cardiovascular','No.',210),
('¿Alguna vez te dijeron que tenías un soplo o algo del corazón?','Historia de la Enfermedad Actual','Cardiovascular','No.',211),
('¿Tuviste dolor de pecho con estrés o nervios?','Historia de la Enfermedad Actual','Cardiovascular','No.',212),
('¿Te duele la panza?','Historia de la Enfermedad Actual','Gastrointestinal','No.',213),
('¿En qué parte de la panza te duele?','Historia de la Enfermedad Actual','Gastrointestinal','No me duele.',214),
('¿Desde cuándo te duele la panza?','Historia de la Enfermedad Actual','Gastrointestinal','No aplica.',215),
('¿El dolor empezó de golpe o de a poco?','Historia de la Enfermedad Actual','Gastrointestinal','No aplica.',216),
('¿El dolor es constante o va y viene?','Historia de la Enfermedad Actual','Gastrointestinal','No aplica.',217),
('¿Cómo es ese dolor?','Historia de la Enfermedad Actual','Gastrointestinal','No aplica.',218),
('¿Te duele después de comer?','Historia de la Enfermedad Actual','Gastrointestinal','No.',219),
('¿Te duele en ayunas?','Historia de la Enfermedad Actual','Gastrointestinal','No.',220),
('¿Te mejora o empeora con la comida?','Historia de la Enfermedad Actual','Gastrointestinal','No aplica.',221),
('¿Tenés acidez o ardor?','Historia de la Enfermedad Actual','Gastrointestinal','No.',222),
('¿Sentís reflujo o que te sube comida?','Historia de la Enfermedad Actual','Gastrointestinal','No.',223),
('¿Tenés náuseas?','Historia de la Enfermedad Actual','Gastrointestinal','No.',224),
('¿Tuviste vómitos?','Historia de la Enfermedad Actual','Gastrointestinal','No.',225),
('¿Cuántas veces vomitaste?','Historia de la Enfermedad Actual','Gastrointestinal','No aplica.',226),
('¿Lo que vomitaste tenía sangre?','Historia de la Enfermedad Actual','Gastrointestinal','No.',227),
('¿Vomitas después de comer?','Historia de la Enfermedad Actual','Gastrointestinal','No.',228),
('¿Tenés la panza hinchada?','Historia de la Enfermedad Actual','Gastrointestinal','No.',229),
('¿Sentís muchos gases?','Historia de la Enfermedad Actual','Gastrointestinal','No.',230),
('¿Eructás más de lo normal?','Historia de la Enfermedad Actual','Gastrointestinal','No.',231),
('¿Te cambió el apetito?','Historia de la Enfermedad Actual','Gastrointestinal','No, como normal.',232),
('¿Tenés menos ganas de comer?','Historia de la Enfermedad Actual','Gastrointestinal','No.',233),
('¿Te llenás rápido al comer?','Historia de la Enfermedad Actual','Gastrointestinal','No.',234),
('¿Te cuesta tragar?','Historia de la Enfermedad Actual','Gastrointestinal','No.',235),
('¿Sentís que la comida se te queda trabada?','Historia de la Enfermedad Actual','Gastrointestinal','No.',236),
('¿Te duele al tragar?','Historia de la Enfermedad Actual','Gastrointestinal','No.',237),
('¿Cómo venís yendo de cuerpo?','Historia de la Enfermedad Actual','Gastrointestinal','Normal.',238),
('¿Vas de cuerpo todos los días o te cuesta?','Historia de la Enfermedad Actual','Gastrointestinal','Voy normal.',239),
('¿Estás con diarrea?','Historia de la Enfermedad Actual','Gastrointestinal','No.',240),
('¿Desde cuándo estás con diarrea?','Historia de la Enfermedad Actual','Gastrointestinal','No aplica.',241),
('¿Cuántas veces por día vas al baño?','Historia de la Enfermedad Actual','Gastrointestinal','Una vez por día, normal.',242),
('¿Las heces salen blandas o líquidas?','Historia de la Enfermedad Actual','Gastrointestinal','No.',243),
('¿Tenés estreñimiento?','Historia de la Enfermedad Actual','Gastrointestinal','No.',244),
('¿Hace cuántos días no vas de cuerpo?','Historia de la Enfermedad Actual','Gastrointestinal','No aplica.',245),
('¿Tenés que hacer fuerza para ir de cuerpo?','Historia de la Enfermedad Actual','Gastrointestinal','No.',246),
('¿Las heces te salieron con sangre?','Historia de la Enfermedad Actual','Gastrointestinal','No.',247),
('¿Las heces te salieron negras?','Historia de la Enfermedad Actual','Gastrointestinal','No.',248),
('¿Notaste moco en la materia fecal?','Historia de la Enfermedad Actual','Gastrointestinal','No.',249),
('¿Tenés urgencia para ir al baño?','Historia de la Enfermedad Actual','Gastrointestinal','No.',250),
('¿Te queda sensación de no terminar?','Historia de la Enfermedad Actual','Gastrointestinal','No.',251),
('¿Te duele al ir de cuerpo?','Historia de la Enfermedad Actual','Gastrointestinal','No.',252),
('¿Tenés picazón o molestia anal?','Historia de la Enfermedad Actual','Gastrointestinal','No.',253),
('¿Notaste que algunos alimentos te caen mal?','Historia de la Enfermedad Actual','Gastrointestinal','No.',254),
('¿La leche, las frituras o lo picante te caen mal?','Historia de la Enfermedad Actual','Gastrointestinal','No.',255),
('¿Empeorás después de comidas pesadas?','Historia de la Enfermedad Actual','Gastrointestinal','No.',256),
('¿Bajaste de peso sin proponértelo?','Historia de la Enfermedad Actual','Gastrointestinal','No.',257),
('¿Tuviste fiebre junto con dolor de panza o diarrea?','Historia de la Enfermedad Actual','Gastrointestinal','No.',258),
('¿Te duele la cintura o la parte baja de la espalda?','Historia de la Enfermedad Actual','Urinario','No.',259),
('¿Estás orinando normal?','Historia de la Enfermedad Actual','Urinario','Sí, normal.',260),
('¿Orinás más seguido de lo habitual?','Historia de la Enfermedad Actual','Urinario','No.',261),
('¿Te levantás de noche a orinar?','Historia de la Enfermedad Actual','Urinario','No.',262),
('¿Orinás en poca cantidad?','Historia de la Enfermedad Actual','Urinario','No.',263),
('¿Te cuesta empezar a orinar?','Historia de la Enfermedad Actual','Urinario','No.',264),
('¿Sentís ardor al orinar?','Historia de la Enfermedad Actual','Urinario','No.',265),
('¿Te duele al orinar?','Historia de la Enfermedad Actual','Urinario','No.',266),
('¿Tenés ganas de orinar a cada rato?','Historia de la Enfermedad Actual','Urinario','No.',267),
('¿Te aguantás poco las ganas?','Historia de la Enfermedad Actual','Urinario','No.',268),
('¿Sentís urgencia para ir al baño?','Historia de la Enfermedad Actual','Urinario','No.',269),
('¿Sentís que vaciás bien la vejiga?','Historia de la Enfermedad Actual','Urinario','Sí.',270),
('¿Te queda sensación de que queda orina?','Historia de la Enfermedad Actual','Urinario','No.',271),
('¿Se te corta el chorro al orinar?','Historia de la Enfermedad Actual','Urinario','No.',272),
('¿El chorro sale flojo?','Historia de la Enfermedad Actual','Urinario','No.',273),
('¿Notaste sangre en la orina?','Historia de la Enfermedad Actual','Urinario','No.',274),
('¿La orina salió muy oscura?','Historia de la Enfermedad Actual','Urinario','No.',275),
('¿La orina tiene olor fuerte o raro?','Historia de la Enfermedad Actual','Urinario','No.',276),
('¿La orina salió turbia?','Historia de la Enfermedad Actual','Urinario','No.',277),
('¿Perdés orina sin querer?','Historia de la Enfermedad Actual','Urinario','No.',278),
('¿Se te escapa al toser o reírte?','Historia de la Enfermedad Actual','Urinario','No.',279),
('¿Se te escapa antes de llegar al baño?','Historia de la Enfermedad Actual','Urinario','No.',280),
('¿Tomás mucha agua y por eso orinás más?','Historia de la Enfermedad Actual','Urinario','No.',281),
('¿Notaste hinchazón en piernas o cara?','Historia de la Enfermedad Actual','Urinario','No.',282),
('¿Tuviste fiebre con molestias para orinar?','Historia de la Enfermedad Actual','Urinario','No.',283),
('¿Sentiste dolor en un costado de la espalda?','Historia de la Enfermedad Actual','Urinario','No.',284),
('¿Ese dolor se corre hacia la ingle?','Historia de la Enfermedad Actual','Urinario','No.',285),
('¿Tuviste cólicos o puntadas en la cintura?','Historia de la Enfermedad Actual','Urinario','No.',286),
('¿Orinás menos que antes?','Historia de la Enfermedad Actual','Urinario','No.',287),
('¿Te cuesta retener la orina?','Historia de la Enfermedad Actual','Urinario','No.',288),
('¿Te duele la cabeza?','Historia de la Enfermedad Actual','Neurológico','No.',289),
('¿Desde cuándo te duele la cabeza?','Historia de la Enfermedad Actual','Neurológico','No aplica.',290),
('¿Dónde te duele la cabeza?','Historia de la Enfermedad Actual','Neurológico','No aplica.',291),
('¿Cómo es ese dolor de cabeza?','Historia de la Enfermedad Actual','Neurológico','No aplica.',292),
('¿Te duele de un lado o de toda la cabeza?','Historia de la Enfermedad Actual','Neurológico','No aplica.',293),
('¿El dolor aparece de golpe o de a poco?','Historia de la Enfermedad Actual','Neurológico','No aplica.',294),
('¿Te pasa seguido o fue algo aislado?','Historia de la Enfermedad Actual','Neurológico','No.',295),
('¿Te molesta la luz cuando te duele la cabeza?','Historia de la Enfermedad Actual','Neurológico','No.',296),
('¿Te molesta el ruido?','Historia de la Enfermedad Actual','Neurológico','No.',297),
('¿Te dan náuseas con el dolor de cabeza?','Historia de la Enfermedad Actual','Neurológico','No.',298),
('¿Sentís mareos?','Historia de la Enfermedad Actual','Neurológico','No.',299),
('¿Es sensación de giro o de inestabilidad?','Historia de la Enfermedad Actual','Neurológico','No aplica.',300),
('¿Te pasa al levantarte o en cualquier momento?','Historia de la Enfermedad Actual','Neurológico','No aplica.',301),
('¿Sentiste que te ibas a desmayar?','Historia de la Enfermedad Actual','Neurológico','No.',302),
('¿Llegaste a desmayarte?','Historia de la Enfermedad Actual','Neurológico','No.',303),
('¿Tuviste convulsiones alguna vez?','Historia de la Enfermedad Actual','Neurológico','No.',304),
('¿Notaste temblores?','Historia de la Enfermedad Actual','Neurológico','No.',305),
('¿En las manos, piernas o en todo el cuerpo?','Historia de la Enfermedad Actual','Neurológico','No aplica.',306),
('¿Te tiemblan las manos en reposo o al hacer algo?','Historia de la Enfermedad Actual','Neurológico','No aplica.',307),
('¿Sentís debilidad en brazos o piernas?','Historia de la Enfermedad Actual','Neurológico','No.',308),
('¿De un lado o de los dos?','Historia de la Enfermedad Actual','Neurológico','No aplica.',309),
('¿Te cuesta agarrar cosas o caminar?','Historia de la Enfermedad Actual','Neurológico','No.',310),
('¿Sentís hormigueos?','Historia de la Enfermedad Actual','Neurológico','No.',311),
('¿Dónde sentís el hormigueo?','Historia de la Enfermedad Actual','Neurológico','No aplica.',312),
('¿Es constante o va y viene?','Historia de la Enfermedad Actual','Neurológico','No aplica.',313),
('¿Perdiste sensibilidad en alguna parte?','Historia de la Enfermedad Actual','Neurológico','No.',314),
('¿Sentís adormecida alguna zona?','Historia de la Enfermedad Actual','Neurológico','No.',315),
('¿Te cuesta coordinar movimientos?','Historia de la Enfermedad Actual','Neurológico','No.',316),
('¿Te sentís torpe al caminar?','Historia de la Enfermedad Actual','Neurológico','No.',317),
('¿Perdiste el equilibrio?','Historia de la Enfermedad Actual','Neurológico','No.',318),
('¿Te caíste por mareo o por perder fuerza?','Historia de la Enfermedad Actual','Neurológico','No.',319),
('¿Te cuesta hablar?','Historia de la Enfermedad Actual','Neurológico','No.',320),
('¿Se te traba la lengua o hablás raro?','Historia de la Enfermedad Actual','Neurológico','No.',321),
('¿Te cuesta encontrar palabras?','Historia de la Enfermedad Actual','Neurológico','No.',322),
('¿Notaste visión borrosa?','Historia de la Enfermedad Actual','Neurológico','No.',323),
('¿Ves doble?','Historia de la Enfermedad Actual','Neurológico','No.',324),
('¿Perdiste visión en algún momento?','Historia de la Enfermedad Actual','Neurológico','No.',325),
('¿Escuchás bien?','Historia de la Enfermedad Actual','Neurológico','Sí.',326),
('¿Notaste zumbidos en los oídos?','Historia de la Enfermedad Actual','Neurológico','No.',327),
('¿Te cuesta concentrarte?','Historia de la Enfermedad Actual','Neurológico','No.',328),
('¿Te olvidás cosas más de lo normal?','Historia de la Enfermedad Actual','Neurológico','No.',329),
('¿Te sentís confundido en algún momento?','Historia de la Enfermedad Actual','Neurológico','No.',330),
('¿Tuviste rigidez en el cuello?','Historia de la Enfermedad Actual','Neurológico','No.',331),
('¿Sentís movimientos raros o sacudones?','Historia de la Enfermedad Actual','Neurológico','No.',332),
('¿Dormís bien?','Historia de la Enfermedad Actual','Salud mental','Sí, duermo bien.',333),
('¿Te cuesta dormirte?','Historia de la Enfermedad Actual','Salud mental','No.',334),
('¿Te despertás varias veces en la noche?','Historia de la Enfermedad Actual','Salud mental','No.',335),
('¿Te despertás muy temprano y no podés seguir durmiendo?','Historia de la Enfermedad Actual','Salud mental','No.',336),
('¿Te levantás descansado?','Historia de la Enfermedad Actual','Salud mental','Sí.',337),
('¿Estás más nervioso o ansioso de lo normal?','Historia de la Enfermedad Actual','Salud mental','No.',338),
('¿Te cuesta relajarte?','Historia de la Enfermedad Actual','Salud mental','No.',339),
('¿Sentís que estás más preocupado de la cuenta?','Historia de la Enfermedad Actual','Salud mental','No.',340),
('¿Te agarran momentos de mucha angustia?','Historia de la Enfermedad Actual','Salud mental','No.',341),
('¿Sentís palpitaciones o ahogo cuando te ponés nervioso?','Historia de la Enfermedad Actual','Salud mental','No.',342),
('¿Te sentís triste?','Historia de la Enfermedad Actual','Salud mental','No.',343),
('¿Estás desanimado últimamente?','Historia de la Enfermedad Actual','Salud mental','No.',344),
('¿Perdiste ganas de hacer cosas que antes te gustaban?','Historia de la Enfermedad Actual','Salud mental','No.',345),
('¿Te aislás más que antes?','Historia de la Enfermedad Actual','Salud mental','No.',346),
('¿Llorás más fácil o sin motivo claro?','Historia de la Enfermedad Actual','Salud mental','No.',347),
('¿Estás más irritable?','Historia de la Enfermedad Actual','Salud mental','No.',348),
('¿Te enojás más fácil que antes?','Historia de la Enfermedad Actual','Salud mental','No.',349),
('¿Te cuesta concentrarte?','Historia de la Enfermedad Actual','Salud mental','No.',350),
('¿Sentís la cabeza cargada por estrés?','Historia de la Enfermedad Actual','Salud mental','No.',351),
('¿Tuviste mucho estrés últimamente?','Historia de la Enfermedad Actual','Salud mental','No.',352),
('¿Cómo venís manejando el estrés?','Historia de la Enfermedad Actual','Salud mental','Bien.',353),
('¿Tu ánimo viene estable?','Historia de la Enfermedad Actual','Salud mental','Sí.',354),
('¿Tenés cambios bruscos de ánimo?','Historia de la Enfermedad Actual','Salud mental','No.',355),
('¿Te sentís con menos energía?','Historia de la Enfermedad Actual','Salud mental','No.',356),
('¿Te cuesta arrancar el día?','Historia de la Enfermedad Actual','Salud mental','No.',357),
('¿Te sentís sobrepasado por tus cosas diarias?','Historia de la Enfermedad Actual','Salud mental','No.',358),
('¿Podés disfrutar tus actividades normales?','Historia de la Enfermedad Actual','Salud mental','Sí.',359),
('¿Te sentís acompañado por la gente cercana?','Historia de la Enfermedad Actual','Salud mental','Sí.',360),
('¿Tenés con quién hablar si te sentís mal?','Historia de la Enfermedad Actual','Salud mental','Sí.',361),
('¿Sentís miedo sin una razón clara?','Historia de la Enfermedad Actual','Salud mental','No.',362),
('¿Te cuesta controlar las preocupaciones?','Historia de la Enfermedad Actual','Salud mental','No.',363),
('¿Estás comiendo normal?','Historia de la Enfermedad Actual','Salud mental','Sí.',364),
('¿El ánimo te cambió el sueño o el apetito?','Historia de la Enfermedad Actual','Salud mental','No.',365),
('¿Te sentís bien en general con vos mismo?','Historia de la Enfermedad Actual','Salud mental','Sí.',366),
('¿Hay algo emocional que te esté afectando estos días?','Historia de la Enfermedad Actual','Salud mental','No.',367),
('¿Te sentís más sensible de lo habitual?','Historia de la Enfermedad Actual','Salud mental','No.',368),
('¿Cómo venís de salud en general?','Antecedentes Personales','Fisiológicos','Bien.',369),
('¿Sos de enfermarte seguido o no?','Antecedentes Personales','Fisiológicos','No, no me enfermo seguido.',370),
('¿Cómo dirías que es tu estado de salud habitual?','Antecedentes Personales','Fisiológicos','Bueno.',371),
('¿Tu peso suele ser estable?','Antecedentes Personales','Fisiológicos','Sí.',372),
('¿Suele cambiarte mucho el apetito?','Antecedentes Personales','Fisiológicos','No.',373),
('¿Dormís bien habitualmente?','Antecedentes Personales','Fisiológicos','Sí.',374),
('¿Descansás bien a la noche en general?','Antecedentes Personales','Fisiológicos','Sí.',375),
('¿Vas de cuerpo normal habitualmente?','Antecedentes Personales','Fisiológicos','Sí.',376),
('¿Orinás normal en tu día a día?','Antecedentes Personales','Fisiológicos','Sí.',377),
('¿Hacés actividad física de forma regular?','Antecedentes Personales','Fisiológicos','Sí, algo de actividad hago.',378),
('¿Tu rutina diaria te permite moverte bastante?','Antecedentes Personales','Fisiológicos','Sí.',379),
('¿Te sentís con energía en tu vida normal?','Antecedentes Personales','Fisiológicos','Sí.',380),
('¿Cómo fue tu salud en la infancia?','Antecedentes Personales','Fisiológicos','Normal.',381),
('¿Tuviste un crecimiento normal cuando eras chico?','Antecedentes Personales','Fisiológicos','Sí.',382),
('¿Te desarrollaste de manera normal?','Antecedentes Personales','Fisiológicos','Sí.',383),
('¿Naciste de término?','Antecedentes Personales','Fisiológicos','Sí.',384),
('¿Al nacer necesitaste algún cuidado especial?','Antecedentes Personales','Fisiológicos','No.',385),
('¿Tuviste problemas importantes en los primeros años de vida?','Antecedentes Personales','Fisiológicos','No.',386),
('¿Te controlás la salud de forma regular?','Antecedentes Personales','Fisiológicos','Sí.',387),
('¿Sos de hacerte chequeos?','Antecedentes Personales','Fisiológicos','Sí.',388),
('¿Tenés alguna enfermedad actualmente?','Antecedentes Personales','Patológicos','No.',389),
('¿Alguna vez te dijeron que tenías presión alta?','Antecedentes Personales','Patológicos','No.',390),
('¿Alguna vez te dijeron que tenías diabetes?','Antecedentes Personales','Patológicos','No.',391),
('¿Tenés colesterol o triglicéridos altos?','Antecedentes Personales','Patológicos','No.',392),
('¿Tenés alguna enfermedad del corazón?','Antecedentes Personales','Patológicos','No.',393),
('¿Tenés alguna enfermedad respiratoria?','Antecedentes Personales','Patológicos','No.',394),
('¿Tenés asma o bronquitis de repetición?','Antecedentes Personales','Patológicos','No.',395),
('¿Tenés alguna enfermedad del estómago o del intestino?','Antecedentes Personales','Patológicos','No.',396),
('¿Tenés gastritis, úlcera o reflujo?','Antecedentes Personales','Patológicos','No.',397),
('¿Tenés alguna enfermedad del hígado?','Antecedentes Personales','Patológicos','No.',398),
('¿Tuviste hepatitis alguna vez?','Antecedentes Personales','Patológicos','No.',399),
('¿Tenés alguna enfermedad de los riñones o de la orina?','Antecedentes Personales','Patológicos','No.',400),
('¿Tuviste infecciones urinarias seguidas?','Antecedentes Personales','Patológicos','No.',401),
('¿Tuviste piedras en el riñón o cólicos renales?','Antecedentes Personales','Patológicos','No.',402),
('¿Tenés alguna enfermedad neurológica?','Antecedentes Personales','Patológicos','No.',403),
('¿Tuviste convulsiones alguna vez?','Antecedentes Personales','Patológicos','No.',404),
('¿Tenés migrañas o dolores de cabeza frecuentes?','Antecedentes Personales','Patológicos','No.',405),
('¿Tenés alguna enfermedad de la tiroides?','Antecedentes Personales','Patológicos','No.',406),
('¿Tenés anemia o te dijeron alguna vez que estabas anémico?','Antecedentes Personales','Patológicos','No.',407),
('¿Tenés problemas de coagulación o sangrados fáciles?','Antecedentes Personales','Patológicos','No.',408),
('¿Te diagnosticaron alguna enfermedad autoinmune?','Antecedentes Personales','Patológicos','No.',409),
('¿Tenés alguna enfermedad en la piel?','Antecedentes Personales','Patológicos','No.',410),
('¿Tenés psoriasis, dermatitis o algo parecido?','Antecedentes Personales','Patológicos','No.',411),
('¿Tuviste alguna enfermedad infecciosa importante?','Antecedentes Personales','Patológicos','No.',412),
('¿Tuviste tuberculosis alguna vez?','Antecedentes Personales','Patológicos','No.',413),
('¿Tuviste alguna enfermedad de transmisión sexual?','Antecedentes Personales','Patológicos','No.',414),
('¿Tuviste COVID con complicaciones?','Antecedentes Personales','Patológicos','No.',415),
('¿Te internaron alguna vez?','Antecedentes Personales','Patológicos','No.',416),
('¿Por qué te internaron?','Antecedentes Personales','Patológicos','No aplica.',417),
('¿Te operaron alguna vez?','Antecedentes Personales','Patológicos','No.',418),
('¿Qué operación te hicieron?','Antecedentes Personales','Patológicos','No aplica.',419),
('¿Tuviste algún accidente importante?','Antecedentes Personales','Patológicos','No.',420),
('¿Te quebraste algún hueso alguna vez?','Antecedentes Personales','Patológicos','No.',421),
('¿Recibiste transfusiones alguna vez?','Antecedentes Personales','Patológicos','No.',422),
('¿Te hicieron estudios o tratamientos largos por alguna enfermedad?','Antecedentes Personales','Patológicos','No.',423),
('¿Tenés alguna discapacidad o limitación física?','Antecedentes Personales','Patológicos','No.',424),
('¿Usás alguna medicación todos los días?','Antecedentes Personales','Medicación','No.',425),
('¿Qué medicación tomás?','Antecedentes Personales','Medicación','No tomo medicación fija.',426),
('¿Tomás remedios aunque sea de vez en cuando?','Antecedentes Personales','Medicación','No.',427),
('¿Tomás algo para la presión, el azúcar o el colesterol?','Antecedentes Personales','Medicación','No.',428),
('¿Usás inhaladores o puff?','Antecedentes Personales','Medicación','No.',429),
('¿Tomás analgésicos seguido?','Antecedentes Personales','Medicación','No.',430),
('¿Tomás antiinflamatorios seguido?','Antecedentes Personales','Medicación','No.',431),
('¿Tomás algo para dormir o para los nervios?','Antecedentes Personales','Medicación','No.',432),
('¿Tomás vitaminas o suplementos?','Antecedentes Personales','Medicación','No.',433),
('¿Tomás yuyos, gotas o remedios naturales?','Antecedentes Personales','Medicación','No.',434),
('¿Usás anticonceptivos o tratamiento hormonal?','Antecedentes Personales','Medicación','No.',435),
('¿Te medicás por tu cuenta?','Antecedentes Personales','Medicación','No.',436),
('¿Recordás bien lo que tomás cuando te indican remedios?','Antecedentes Personales','Medicación','Sí.',437),
('¿Sos de terminar los tratamientos cuando te los dan?','Antecedentes Personales','Medicación','Sí.',438),
('¿Te hace mal alguna medicación?','Antecedentes Personales','Alergias','No.',439),
('¿Tenés alergia a algún remedio?','Antecedentes Personales','Alergias','No.',440),
('¿A cuál remedio sos alérgico?','Antecedentes Personales','Alergias','No aplica.',441),
('¿Qué te pasa cuando lo tomás?','Antecedentes Personales','Alergias','No aplica.',442),
('¿Tenés alergia a alimentos?','Antecedentes Personales','Alergias','No.',443),
('¿A qué alimento?','Antecedentes Personales','Alergias','No aplica.',444),
('¿Tenés alergia al polvo, al polen o a los animales?','Antecedentes Personales','Alergias','No.',445),
('¿Tenés rinitis o alergias respiratorias?','Antecedentes Personales','Alergias','No.',446),
('¿Te salen ronchas o picazón por algo?','Antecedentes Personales','Alergias','No.',447),
('¿Te hizo reacción alguna picadura de insecto?','Antecedentes Personales','Alergias','No.',448),
('¿Tenés alergia al látex?','Antecedentes Personales','Alergias','No.',449),
('¿Tenés alergia a alguna crema, jabón o producto de la piel?','Antecedentes Personales','Alergias','No.',450),
('¿Alguna vez te faltó el aire por una alergia?','Antecedentes Personales','Alergias','No.',451),
('¿Alguna vez tuviste una reacción alérgica fuerte?','Antecedentes Personales','Alergias','No.',452),
('¿Fumás?','Antecedentes Personales','Hábitos','No.',453),
('¿Fumaste alguna vez?','Antecedentes Personales','Hábitos','No.',454),
('¿Cuántos cigarrillos por día fumás?','Antecedentes Personales','Hábitos','No aplica.',455),
('¿Hace cuánto fumás?','Antecedentes Personales','Hábitos','No aplica.',456),
('¿Hace cuánto dejaste de fumar?','Antecedentes Personales','Hábitos','No aplica.',457),
('¿Vapeás o usás cigarrillo electrónico?','Antecedentes Personales','Hábitos','No.',458),
('¿Tomás alcohol?','Antecedentes Personales','Hábitos','No o muy de vez en cuando.',459),
('¿Qué solés tomar?','Antecedentes Personales','Hábitos','No aplica.',460),
('¿Cada cuánto tomás alcohol?','Antecedentes Personales','Hábitos','Muy de vez en cuando.',461),
('¿Tomás mucho en una sola vez?','Antecedentes Personales','Hábitos','No.',462),
('¿Consumís alguna droga?','Antecedentes Personales','Hábitos','No.',463),
('¿Consumiste alguna vez?','Antecedentes Personales','Hábitos','No.',464),
('¿Tomás mucho café, mate o bebidas energizantes?','Antecedentes Personales','Hábitos','No en exceso.',465),
('¿Cuántos cafés, mates o energizantes tomás por día?','Antecedentes Personales','Hábitos','No aplica.',466),
('¿Cómo es tu alimentación en general?','Antecedentes Personales','Hábitos','Bastante equilibrada.',467),
('¿Comés variado?','Antecedentes Personales','Hábitos','Sí.',468),
('¿Comés frutas y verduras seguido?','Antecedentes Personales','Hábitos','Sí.',469),
('¿Comés muchas frituras o comida rápida?','Antecedentes Personales','Hábitos','No.',470),
('¿Le ponés mucha sal a las comidas?','Antecedentes Personales','Hábitos','No.',471),
('¿Tomás suficiente agua por día?','Antecedentes Personales','Hábitos','Sí.',472),
('¿Hacés actividad física?','Antecedentes Personales','Hábitos','Sí.',473),
('¿Qué actividad física hacés?','Antecedentes Personales','Hábitos','Camino o hago ejercicio suave.',474),
('¿Cuántas veces por semana te movés o entrenás?','Antecedentes Personales','Hábitos','Varias veces por semana.',475),
('¿Pasás mucho tiempo sentado?','Antecedentes Personales','Hábitos','Sí, por trabajo, pero me muevo.',476),
('¿Cómo es tu rutina diaria?','Antecedentes Personales','Hábitos','Bastante ordenada.',477),
('¿Tenés horarios regulares para comer?','Antecedentes Personales','Hábitos','Sí.',478),
('¿Desayunás habitualmente?','Antecedentes Personales','Hábitos','Sí.',479),
('¿Picoteás mucho entre comidas?','Antecedentes Personales','Hábitos','No.',480),
('¿Sos de automedicarte?','Antecedentes Personales','Hábitos','No.',481),
('¿Te hacés controles de salud de rutina?','Antecedentes Personales','Hábitos','Sí.',482),
('¿Dormís bien en general?','Antecedentes Personales','Sueño','Sí.',483),
('¿Cuántas horas dormís por noche?','Antecedentes Personales','Sueño','Alrededor de 7 u 8 horas.',484),
('¿Te cuesta dormirte?','Antecedentes Personales','Sueño','No.',485),
('¿Te despertás durante la noche?','Antecedentes Personales','Sueño','No.',486),
('¿Te levantás descansado?','Antecedentes Personales','Sueño','Sí.',487),
('¿Tenés sueño durante el día?','Antecedentes Personales','Sueño','No.',488),
('¿Dormís siesta?','Antecedentes Personales','Sueño','A veces.',489),
('¿Roncás?','Antecedentes Personales','Sueño','No.',490),
('¿Alguna vez te dijeron que dejás de respirar al dormir?','Antecedentes Personales','Sueño','No.',491),
('¿Te despertás con dolor de cabeza o la boca seca?','Antecedentes Personales','Sueño','No.',492),
('¿Trabajás de noche o cambiás mucho los horarios?','Antecedentes Personales','Sueño','No.',493),
('¿Usás el celular o pantallas antes de dormir?','Antecedentes Personales','Sueño','Sí, a veces.',494),
('¿Tu sueño suele ser reparador?','Antecedentes Personales','Sueño','Sí.',495),
('¿Tenés las vacunas al día?','Antecedentes Personales','Vacunación','Sí.',496),
('¿Recordás cuándo te diste la última vacuna antitetánica?','Antecedentes Personales','Vacunación','No exactamente, pero estoy al día.',497),
('¿Te das la vacuna de la gripe cuando corresponde?','Antecedentes Personales','Vacunación','Sí, cuando corresponde.',498),
('¿Te diste las vacunas de COVID?','Antecedentes Personales','Vacunación','Sí.',499),
('¿Tenés el calendario de vacunas completo?','Antecedentes Personales','Vacunación','Sí.',500),
('¿Te falta alguna vacuna que sepas?','Antecedentes Personales','Vacunación','No.',501),
('¿Te dieron vacunas por trabajo, viaje o estudio?','Antecedentes Personales','Vacunación','No hizo falta.',502),
('¿Tuviste alguna reacción importante a una vacuna?','Antecedentes Personales','Vacunación','No.',503),
('¿Tenés controles de salud sexual o reproductiva?','Antecedentes Personales','Sexual','Sí.',504),
('¿Tenés vida sexual activa?','Antecedentes Personales','Sexual','Sí.',505),
('¿Tenés una sola pareja o más de una?','Antecedentes Personales','Sexual','Una sola pareja.',506),
('¿Usás preservativo o algún método de cuidado?','Antecedentes Personales','Sexual','Sí.',507),
('¿Usás algún método anticonceptivo?','Antecedentes Personales','Sexual','Sí o no, según corresponda.',508),
('¿Tuviste alguna infección de transmisión sexual?','Antecedentes Personales','Sexual','No.',509),
('¿Te hiciste controles de salud sexual alguna vez?','Antecedentes Personales','Sexual','Sí.',510),
('¿Tuviste relaciones sin cuidado alguna vez?','Antecedentes Personales','Sexual','No.',511),
('¿Hay algo de tu vida sexual que te preocupe?','Antecedentes Personales','Sexual','No.',512),
('¿Tenés dolor o molestias en las relaciones?','Antecedentes Personales','Sexual','No.',513),
('¿Notaste secreciones, lesiones o algo raro en la zona íntima?','Antecedentes Personales','Sexual','No.',514),
('¿Cómo es el lugar donde vivís?','Antecedentes Personales','Medio','Bueno.',515),
('¿Vivís en casa o departamento?','Antecedentes Personales','Medio','En un departamento.',516),
('¿Con cuántas personas convivís?','Antecedentes Personales','Medio','Con una o dos personas.',517),
('¿Tenés agua potable en tu casa?','Antecedentes Personales','Medio','Sí.',518),
('¿Tenés cloacas o un baño en buenas condiciones?','Antecedentes Personales','Medio','Sí.',519),
('¿En tu casa hay humedad, moho o mucho polvo?','Antecedentes Personales','Medio','No.',520),
('¿Hay buena ventilación en tu casa?','Antecedentes Personales','Medio','Sí.',521),
('¿Tenés mascotas?','Antecedentes Personales','Medio','No.',522),
('¿Estás en contacto con animales por trabajo o en tu casa?','Antecedentes Personales','Medio','No.',523),
('¿Tu trabajo te expone a polvo, humo o químicos?','Antecedentes Personales','Medio','No.',524),
('¿Trabajás con mucho ruido o calor?','Antecedentes Personales','Medio','No.',525),
('¿Usás protección en el trabajo si hace falta?','Antecedentes Personales','Medio','Sí.',526),
('¿Viajaste últimamente a algún lugar distinto?','Antecedentes Personales','Medio','No.',527),
('¿Estuviste en contacto con alguien enfermo?','Antecedentes Personales','Medio','No.',528),
('¿Tenés acceso fácil a comida y agua seguras?','Antecedentes Personales','Medio','Sí.',529),
('¿Te sentís seguro en tu casa y en tu entorno?','Antecedentes Personales','Medio','Sí.',530),
('¿Tu entorno te genera mucho estrés?','Antecedentes Personales','Medio','No.',531),
('¿Tenés apoyo de la gente con la que vivís?','Antecedentes Personales','Medio','Sí.',532),
('¿Cómo son tus condiciones de trabajo en general?','Antecedentes Personales','Medio','Buenas.',533),
('¿Tu casa tiene escaleras o barreras que te compliquen?','Antecedentes Personales','Medio','No.',534),
('¿Tuviste exposición reciente a humo, pintura o productos fuertes?','Antecedentes Personales','Medio','No.',535),
('¿Solés usar repelente o protección si hace falta?','Antecedentes Personales','Medio','Sí.',536),
('¿Vivís o trabajás en un lugar con mucha gente?','Antecedentes Personales','Medio','No.',537),
('¿En tu familia hay alguien con presión alta?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',538),
('¿Quién tiene o tuvo presión alta en tu familia?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No aplica.',539),
('¿En tu familia hay diabetes?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',540),
('¿Quién tiene o tuvo diabetes en tu familia?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No aplica.',541),
('¿En tu familia hay colesterol alto?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',542),
('¿En tu familia hubo infartos?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',543),
('¿A qué edad tuvo el infarto ese familiar?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No aplica.',544),
('¿En tu familia hubo problemas del corazón?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',545),
('¿Alguien tuvo insuficiencia cardíaca o arritmias?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',546),
('¿En tu familia hubo ACV o derrames?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',547),
('¿Quién tuvo ACV en tu familia?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No aplica.',548),
('¿En tu familia hay asma?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',549),
('¿En tu familia hay alergias importantes?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',550),
('¿En tu familia hubo tuberculosis?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',551),
('¿En tu familia hay problemas de tiroides?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',552),
('¿Quién tiene o tuvo problemas de tiroides?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No aplica.',553),
('¿En tu familia hay anemia o problemas de la sangre?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',554),
('¿En tu familia hay problemas de sangrado o coagulación?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',555),
('¿En tu familia hay enfermedades autoinmunes?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',556),
('¿En tu familia hay artritis u otras enfermedades reumáticas?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',557),
('¿En tu familia hubo enfermedades del hígado?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',558),
('¿En tu familia hubo hepatitis?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',559),
('¿En tu familia hay problemas renales?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',560),
('¿Alguien en tu familia tuvo diálisis o insuficiencia renal?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',561),
('¿En tu familia hubo piedras en el riñón?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',562),
('¿En tu familia hay enfermedades neurológicas?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',563),
('¿En tu familia hubo epilepsia o convulsiones?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',564),
('¿En tu familia hubo Alzheimer o problemas de memoria?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',565),
('¿En tu familia hubo Parkinson o temblores?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',566),
('¿En tu familia hay depresión, ansiedad u otros problemas emocionales?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',567),
('¿En tu familia hubo cáncer?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',568),
('¿Qué tipo de cáncer hubo en tu familia?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No aplica.',569),
('¿Fue en familiares cercanos?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No aplica.',570),
('¿En tu familia hubo cáncer de mama?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',571),
('¿En tu familia hubo cáncer de ovario?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',572),
('¿En tu familia hubo cáncer de útero?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',573),
('¿En tu familia hubo cáncer de próstata?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',574),
('¿En tu familia hubo cáncer de colon o intestino?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',575),
('¿En tu familia hubo pólipos o problemas importantes en el colon?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',576),
('¿En tu familia hubo cáncer de pulmón?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',577),
('¿En tu familia hubo cáncer de piel?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',578),
('¿En tu familia hay obesidad marcada?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',579),
('¿En tu familia hay enfermedades hereditarias conocidas?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',580),
('¿Te dijeron alguna vez que en tu familia hay una enfermedad que se repite?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',581),
('¿Tus padres viven?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','Sí.',582),
('¿Cómo es la salud de tus padres?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','Buena.',583),
('¿Tus hermanos están sanos?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','Sí.',584),
('¿Tus abuelos tuvieron alguna enfermedad importante?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',585),
('¿Hubo muertes tempranas en tu familia?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',586),
('¿Sabés de qué fallecieron tus familiares más cercanos?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No aplica.',587),
('¿Hay alguna enfermedad que te preocupe por antecedentes de familia?','Antecedentes Hereditarios y Familiares','Antecedentes familiares','No.',588);
